dist: xenial
language: minimal

matrix:
    include:
        - name: "Build direwolf-git"
          env: TARGET=build PACKAGE=direwolf-git

        - name: "Build dwarview-git"
          env: TARGET=build PACKAGE=dwarview-git

        - name: "Build kalibrate-bladerf-git"
          env: TARGET=build PACKAGE=kalibrate-bladerf-git

        - name: "Build nerd-fonts-roboto-mono"
          env: TARGET=build PACKAGE=nerd-fonts-roboto-mono

        - name: "Build nerd-fonts-droid-sans-mono"
          env: TARGET=build PACKAGE=nerd-fonts-droid-sans-mono

        - name: "Build python-grpcio-tools"
          env: TARGET=build PACKAGE=python-grpcio-tools
        - name: "Check version of python-grpcio-tools"
          env: TARGET=version PACKAGE=python-grpcio-tools

        - name: "Build python-projectq"
          env: TARGET=build PACKAGE=python-projectq
        - name: "Check version of python-projectq"
          env: TARGET=version PACKAGE=python-projectq

        - name: "Build python-pyxel"
          env: TARGET=build PACKAGE=python-pyxel
        - name: "Check version of python-pyxel"
          env: TARGET=version PACKAGE=python-pyxel

        - name: "Build python-vunit_hdl"
          env: TARGET=build PACKAGE=python-vunit_hdl
        - name: "Check version of python-vunit_hdl"
          env: TARGET=version PACKAGE=python-vunit_hdl

        - name: "Build steam-fonts"
          env: TARGET=build PACKAGE=steam-fonts

        - name: "Build usbsoftrock"
          env: TARGET=build PACKAGE=usbsoftrock

        - name: "Build vna_j"
          env: TARGET=build PACKAGE=vna_j
        - name: "Check version of vna_j"
          env: TARGET=version PACKAGE=vna_j

before_install:
    - .travis/prepare.sh $TARGET

script:
    - .travis/run-test.sh $TARGET $PACKAGE
